spring:
  application:
    name: store
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
  cache:
    type: redis
    redis:
      time-to-live: 60000 # 1 minute in milliseconds
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
