spring:
  application:
    name: store
  cache:
    type: redis
    redis:
      time-to-live: 60000 # 1 minute in milliseconds
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  profiles:
    active: dev
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}
  resilience4j.ratelimiter:
    configs:
      default:
        limitForPeriod: 1
        limitRefreshPeriod: 1 # in sec
        timeoutDuration: 0
    instances:
      productService:
        baseConfig: default
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
